# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import api_usage_pb2 as finazon__grpc__python_dot_api__usage__pb2


class ApiUsageServiceStub(object):
    """*
    ApiUsageService provide access to quota usage
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetApiUsage = channel.unary_unary(
                '/finazon.ApiUsageService/GetApiUsage',
                request_serializer=finazon__grpc__python_dot_api__usage__pb2.GetApiUsageRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_api__usage__pb2.GetApiUsageResponse.FromString,
                )


class ApiUsageServiceServicer(object):
    """*
    ApiUsageService provide access to quota usage
    """

    def GetApiUsage(self, request, context):
        """Get a list of products with quota limit/usage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiUsageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetApiUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiUsage,
                    request_deserializer=finazon__grpc__python_dot_api__usage__pb2.GetApiUsageRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_api__usage__pb2.GetApiUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.ApiUsageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ApiUsageService(object):
    """*
    ApiUsageService provide access to quota usage
    """

    @staticmethod
    def GetApiUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.ApiUsageService/GetApiUsage',
            finazon__grpc__python_dot_api__usage__pb2.GetApiUsageRequest.SerializeToString,
            finazon__grpc__python_dot_api__usage__pb2.GetApiUsageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
