"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ApiUsageItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: builtins.int
    APICALLS_FIELD_NUMBER: builtins.int
    HISTORICALAPICALLS_FIELD_NUMBER: builtins.int
    product: builtins.str
    @property
    def apiCalls(self) -> global___ApiCalls: ...
    @property
    def historicalApiCalls(self) -> global___ApiCalls: ...
    def __init__(
        self,
        *,
        product: builtins.str = ...,
        apiCalls: global___ApiCalls | None = ...,
        historicalApiCalls: global___ApiCalls | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["apiCalls", b"apiCalls", "historicalApiCalls", b"historicalApiCalls"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["apiCalls", b"apiCalls", "historicalApiCalls", b"historicalApiCalls", "product", b"product"]) -> None: ...

global___ApiUsageItem = ApiUsageItem

@typing.final
class ApiCalls(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIMIT_FIELD_NUMBER: builtins.int
    USAGE_FIELD_NUMBER: builtins.int
    limit: builtins.int
    usage: builtins.int
    def __init__(
        self,
        *,
        limit: builtins.int = ...,
        usage: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "usage", b"usage"]) -> None: ...

global___ApiCalls = ApiCalls

@typing.final
class GetApiUsageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: builtins.int
    product: builtins.str
    def __init__(
        self,
        *,
        product: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["product", b"product"]) -> None: ...

global___GetApiUsageRequest = GetApiUsageRequest

@typing.final
class GetApiUsageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ApiUsageItem]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___ApiUsageItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___GetApiUsageResponse = GetApiUsageResponse
