# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/api_usage.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#finazon_grpc_python/api_usage.proto\x12\x07\x66inazon\"s\n\x0c\x41piUsageItem\x12\x0f\n\x07product\x18\x01 \x01(\t\x12#\n\x08\x61piCalls\x18\x02 \x01(\x0b\x32\x11.finazon.ApiCalls\x12-\n\x12historicalApiCalls\x18\x03 \x01(\x0b\x32\x11.finazon.ApiCalls\"(\n\x08\x41piCalls\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\r\n\x05usage\x18\x02 \x01(\x05\"%\n\x12GetApiUsageRequest\x12\x0f\n\x07product\x18\x01 \x01(\t\"<\n\x13GetApiUsageResponse\x12%\n\x06result\x18\x01 \x03(\x0b\x32\x15.finazon.ApiUsageItem2]\n\x0f\x41piUsageService\x12J\n\x0bGetApiUsage\x12\x1b.finazon.GetApiUsageRequest\x1a\x1c.finazon.GetApiUsageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.api_usage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APIUSAGEITEM']._serialized_start=48
  _globals['_APIUSAGEITEM']._serialized_end=163
  _globals['_APICALLS']._serialized_start=165
  _globals['_APICALLS']._serialized_end=205
  _globals['_GETAPIUSAGEREQUEST']._serialized_start=207
  _globals['_GETAPIUSAGEREQUEST']._serialized_end=244
  _globals['_GETAPIUSAGERESPONSE']._serialized_start=246
  _globals['_GETAPIUSAGERESPONSE']._serialized_end=306
  _globals['_APIUSAGESERVICE']._serialized_start=308
  _globals['_APIUSAGESERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
