"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BinanceTimeSeries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    TRADES_FIELD_NUMBER: builtins.int
    BASE_VOLUME_FIELD_NUMBER: builtins.int
    QUOTE_VOLUME_FIELD_NUMBER: builtins.int
    TAKER_BUY_BASE_ASSET_VOLUME_FIELD_NUMBER: builtins.int
    TAKER_BUY_QUOTE_ASSET_VOLUME_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    open: builtins.float
    close: builtins.float
    high: builtins.float
    low: builtins.float
    trades: builtins.float
    base_volume: builtins.float
    quote_volume: builtins.float
    taker_buy_base_asset_volume: builtins.float
    taker_buy_quote_asset_volume: builtins.float
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
        open: builtins.float = ...,
        close: builtins.float = ...,
        high: builtins.float = ...,
        low: builtins.float = ...,
        trades: builtins.float = ...,
        base_volume: builtins.float = ...,
        quote_volume: builtins.float = ...,
        taker_buy_base_asset_volume: builtins.float = ...,
        taker_buy_quote_asset_volume: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["base_volume", b"base_volume", "close", b"close", "high", b"high", "low", b"low", "open", b"open", "quote_volume", b"quote_volume", "taker_buy_base_asset_volume", b"taker_buy_base_asset_volume", "taker_buy_quote_asset_volume", b"taker_buy_quote_asset_volume", "timestamp", b"timestamp", "trades", b"trades"]) -> None: ...

global___BinanceTimeSeries = BinanceTimeSeries

@typing.final
class GetBinanceTimeSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    START_AT_FIELD_NUMBER: builtins.int
    END_AT_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    interval: builtins.str
    start_at: builtins.int
    end_at: builtins.int
    page: builtins.int
    page_size: builtins.int
    order: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        interval: builtins.str = ...,
        start_at: builtins.int = ...,
        end_at: builtins.int = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        order: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["end_at", b"end_at", "interval", b"interval", "order", b"order", "page", b"page", "page_size", b"page_size", "start_at", b"start_at", "ticker", b"ticker"]) -> None: ...

global___GetBinanceTimeSeriesRequest = GetBinanceTimeSeriesRequest

@typing.final
class GetBinanceTimeSeriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BinanceTimeSeries]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___BinanceTimeSeries] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___GetBinanceTimeSeriesResponse = GetBinanceTimeSeriesResponse
