# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/binance.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!finazon_grpc_python/binance.proto\x12\x07\x66inazon\"\xe4\x01\n\x11\x42inanceTimeSeries\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\r\n\x05\x63lose\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\x12\x0e\n\x06trades\x18\x06 \x01(\x01\x12\x13\n\x0b\x62\x61se_volume\x18\x07 \x01(\x01\x12\x14\n\x0cquote_volume\x18\x08 \x01(\x01\x12#\n\x1btaker_buy_base_asset_volume\x18\t \x01(\x01\x12$\n\x1ctaker_buy_quote_asset_volume\x18\n \x01(\x01\"\xad\x01\n\x1bGetBinanceTimeSeriesRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\t\x12\x10\n\x08start_at\x18\x05 \x01(\x03\x12\x0e\n\x06\x65nd_at\x18\x06 \x01(\x03\x12\x0c\n\x04page\x18\x07 \x01(\x05\x12\x11\n\tpage_size\x18\x08 \x01(\x05\x12\r\n\x05order\x18\t \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05R\x08timezoneR\x04\x64\x61te\"J\n\x1cGetBinanceTimeSeriesResponse\x12*\n\x06result\x18\x01 \x03(\x0b\x32\x1a.finazon.BinanceTimeSeries2p\n\x0e\x42inanceService\x12^\n\rGetTimeSeries\x12$.finazon.GetBinanceTimeSeriesRequest\x1a%.finazon.GetBinanceTimeSeriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.binance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BINANCETIMESERIES']._serialized_start=47
  _globals['_BINANCETIMESERIES']._serialized_end=275
  _globals['_GETBINANCETIMESERIESREQUEST']._serialized_start=278
  _globals['_GETBINANCETIMESERIESREQUEST']._serialized_end=451
  _globals['_GETBINANCETIMESERIESRESPONSE']._serialized_start=453
  _globals['_GETBINANCETIMESERIESRESPONSE']._serialized_end=527
  _globals['_BINANCESERVICE']._serialized_start=529
  _globals['_BINANCESERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
