# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/crypto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n finazon_grpc_python/crypto.proto\x12\x07\x66inazon\"m\n\x10\x43ryptoTimeSeries\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\r\n\x05\x63lose\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"\xae\x01\n\x1aGetCryptoTimeSeriesRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08timezone\x18\x02 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\t\x12\x10\n\x08start_at\x18\x05 \x01(\x03\x12\x0e\n\x06\x65nd_at\x18\x06 \x01(\x03\x12\x0c\n\x04page\x18\x07 \x01(\x05\x12\x11\n\tpage_size\x18\x08 \x01(\x05\x12\r\n\x05order\x18\t \x01(\tJ\x04\x08\x04\x10\x05R\x04\x64\x61te\"H\n\x1bGetCryptoTimeSeriesResponse\x12)\n\x06result\x18\x01 \x03(\x0b\x32\x19.finazon.CryptoTimeSeries2m\n\rCryptoService\x12\\\n\rGetTimeSeries\x12#.finazon.GetCryptoTimeSeriesRequest\x1a$.finazon.GetCryptoTimeSeriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.crypto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CRYPTOTIMESERIES']._serialized_start=45
  _globals['_CRYPTOTIMESERIES']._serialized_end=154
  _globals['_GETCRYPTOTIMESERIESREQUEST']._serialized_start=157
  _globals['_GETCRYPTOTIMESERIESREQUEST']._serialized_end=331
  _globals['_GETCRYPTOTIMESERIESRESPONSE']._serialized_start=333
  _globals['_GETCRYPTOTIMESERIESRESPONSE']._serialized_end=405
  _globals['_CRYPTOSERVICE']._serialized_start=407
  _globals['_CRYPTOSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
