# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import crypto_pb2 as finazon__grpc__python_dot_crypto__pb2


class CryptoServiceStub(object):
    """*
    CryptoService provide access to time series data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimeSeries = channel.unary_unary(
                '/finazon.CryptoService/GetTimeSeries',
                request_serializer=finazon__grpc__python_dot_crypto__pb2.GetCryptoTimeSeriesRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_crypto__pb2.GetCryptoTimeSeriesResponse.FromString,
                )


class CryptoServiceServicer(object):
    """*
    CryptoService provide access to time series data
    """

    def GetTimeSeries(self, request, context):
        """Get time series data for any given ticker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CryptoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeSeries,
                    request_deserializer=finazon__grpc__python_dot_crypto__pb2.GetCryptoTimeSeriesRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_crypto__pb2.GetCryptoTimeSeriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.CryptoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CryptoService(object):
    """*
    CryptoService provide access to time series data
    """

    @staticmethod
    def GetTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.CryptoService/GetTimeSeries',
            finazon__grpc__python_dot_crypto__pb2.GetCryptoTimeSeriesRequest.SerializeToString,
            finazon__grpc__python_dot_crypto__pb2.GetCryptoTimeSeriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
