# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import exchange_pb2 as finazon__grpc__python_dot_exchange__pb2


class ExchangeServiceStub(object):
    """*
    ExchangeService provide access to Finazon exchange data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarketsCrypto = channel.unary_unary(
                '/finazon.ExchangeService/GetMarketsCrypto',
                request_serializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsCryptoRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsCryptoResponse.FromString,
                )
        self.GetMarketsStocks = channel.unary_unary(
                '/finazon.ExchangeService/GetMarketsStocks',
                request_serializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsStocksRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsStocksResponse.FromString,
                )


class ExchangeServiceServicer(object):
    """*
    ExchangeService provide access to Finazon exchange data
    """

    def GetMarketsCrypto(self, request, context):
        """Returns a list of supported crypto markets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketsStocks(self, request, context):
        """Returns a list of supported stock markets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarketsCrypto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketsCrypto,
                    request_deserializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsCryptoRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsCryptoResponse.SerializeToString,
            ),
            'GetMarketsStocks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketsStocks,
                    request_deserializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsStocksRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_exchange__pb2.GetMarketsStocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.ExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExchangeService(object):
    """*
    ExchangeService provide access to Finazon exchange data
    """

    @staticmethod
    def GetMarketsCrypto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.ExchangeService/GetMarketsCrypto',
            finazon__grpc__python_dot_exchange__pb2.GetMarketsCryptoRequest.SerializeToString,
            finazon__grpc__python_dot_exchange__pb2.GetMarketsCryptoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMarketsStocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.ExchangeService/GetMarketsStocks',
            finazon__grpc__python_dot_exchange__pb2.GetMarketsStocksRequest.SerializeToString,
            finazon__grpc__python_dot_exchange__pb2.GetMarketsStocksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
