# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/exchange.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"finazon_grpc_python/exchange.proto\x12\x07\x66inazon\":\n\x17GetMarketsCryptoRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"7\n\x19MarketsCryptoResponseItem\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"N\n\x18GetMarketsCryptoResponse\x12\x32\n\x06result\x18\x01 \x03(\x0b\x32\".finazon.MarketsCryptoResponseItem\"g\n\x17GetMarketsStocksRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0c\n\x04page\x18\x04 \x01(\x05\x12\x11\n\tpage_size\x18\x05 \x01(\x05\"G\n\x19MarketsStocksResponseItem\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0b\n\x03mic\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"N\n\x18GetMarketsStocksResponse\x12\x32\n\x06result\x18\x01 \x03(\x0b\x32\".finazon.MarketsStocksResponseItem2\xc7\x01\n\x0f\x45xchangeService\x12Y\n\x10GetMarketsCrypto\x12 .finazon.GetMarketsCryptoRequest\x1a!.finazon.GetMarketsCryptoResponse\"\x00\x12Y\n\x10GetMarketsStocks\x12 .finazon.GetMarketsStocksRequest\x1a!.finazon.GetMarketsStocksResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.exchange_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETMARKETSCRYPTOREQUEST']._serialized_start=47
  _globals['_GETMARKETSCRYPTOREQUEST']._serialized_end=105
  _globals['_MARKETSCRYPTORESPONSEITEM']._serialized_start=107
  _globals['_MARKETSCRYPTORESPONSEITEM']._serialized_end=162
  _globals['_GETMARKETSCRYPTORESPONSE']._serialized_start=164
  _globals['_GETMARKETSCRYPTORESPONSE']._serialized_end=242
  _globals['_GETMARKETSSTOCKSREQUEST']._serialized_start=244
  _globals['_GETMARKETSSTOCKSREQUEST']._serialized_end=347
  _globals['_MARKETSSTOCKSRESPONSEITEM']._serialized_start=349
  _globals['_MARKETSSTOCKSRESPONSEITEM']._serialized_end=420
  _globals['_GETMARKETSSTOCKSRESPONSE']._serialized_start=422
  _globals['_GETMARKETSSTOCKSRESPONSE']._serialized_end=500
  _globals['_EXCHANGESERVICE']._serialized_start=503
  _globals['_EXCHANGESERVICE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
