"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ForexTimeSeries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    open: builtins.float
    close: builtins.float
    high: builtins.float
    low: builtins.float
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
        open: builtins.float = ...,
        close: builtins.float = ...,
        high: builtins.float = ...,
        low: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["close", b"close", "high", b"high", "low", b"low", "open", b"open", "timestamp", b"timestamp"]) -> None: ...

global___ForexTimeSeries = ForexTimeSeries

@typing_extensions.final
class GetForexTimeSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    TIMEZONE_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    START_AT_FIELD_NUMBER: builtins.int
    END_AT_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    timezone: builtins.str
    interval: builtins.str
    start_at: builtins.int
    end_at: builtins.int
    page: builtins.int
    page_size: builtins.int
    order: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        timezone: builtins.str = ...,
        interval: builtins.str = ...,
        start_at: builtins.int = ...,
        end_at: builtins.int = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        order: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_at", b"end_at", "interval", b"interval", "order", b"order", "page", b"page", "page_size", b"page_size", "start_at", b"start_at", "ticker", b"ticker", "timezone", b"timezone"]) -> None: ...

global___GetForexTimeSeriesRequest = GetForexTimeSeriesRequest

@typing_extensions.final
class GetForexTimeSeriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ForexTimeSeries]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___ForexTimeSeries] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result", b"result"]) -> None: ...

global___GetForexTimeSeriesResponse = GetForexTimeSeriesResponse
