# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/forex.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x66inazon_grpc_python/forex.proto\x12\x07\x66inazon\"\\\n\x0f\x46orexTimeSeries\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\r\n\x05\x63lose\x18\x03 \x01(\x01\x12\x0c\n\x04high\x18\x04 \x01(\x01\x12\x0b\n\x03low\x18\x05 \x01(\x01\"\xab\x01\n\x19GetForexTimeSeriesRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\t\x12\x10\n\x08start_at\x18\x05 \x01(\x03\x12\x0e\n\x06\x65nd_at\x18\x06 \x01(\x03\x12\x0c\n\x04page\x18\x07 \x01(\x05\x12\x11\n\tpage_size\x18\x08 \x01(\x05\x12\r\n\x05order\x18\t \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x04\x10\x05R\x08timezoneR\x04\x64\x61te\"F\n\x1aGetForexTimeSeriesResponse\x12(\n\x06result\x18\x01 \x03(\x0b\x32\x18.finazon.ForexTimeSeries2j\n\x0c\x46orexService\x12Z\n\rGetTimeSeries\x12\".finazon.GetForexTimeSeriesRequest\x1a#.finazon.GetForexTimeSeriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.forex_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FOREXTIMESERIES']._serialized_start=44
  _globals['_FOREXTIMESERIES']._serialized_end=136
  _globals['_GETFOREXTIMESERIESREQUEST']._serialized_start=139
  _globals['_GETFOREXTIMESERIESREQUEST']._serialized_end=310
  _globals['_GETFOREXTIMESERIESRESPONSE']._serialized_start=312
  _globals['_GETFOREXTIMESERIESRESPONSE']._serialized_end=382
  _globals['_FOREXSERVICE']._serialized_start=384
  _globals['_FOREXSERVICE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
