# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import forex_pb2 as finazon__grpc__python_dot_forex__pb2


class ForexServiceStub(object):
    """*
    ForexService provide access to time series data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimeSeries = channel.unary_unary(
                '/finazon.ForexService/GetTimeSeries',
                request_serializer=finazon__grpc__python_dot_forex__pb2.GetForexTimeSeriesRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_forex__pb2.GetForexTimeSeriesResponse.FromString,
                )


class ForexServiceServicer(object):
    """*
    ForexService provide access to time series data
    """

    def GetTimeSeries(self, request, context):
        """Get time series data for any given ticker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeSeries,
                    request_deserializer=finazon__grpc__python_dot_forex__pb2.GetForexTimeSeriesRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_forex__pb2.GetForexTimeSeriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.ForexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ForexService(object):
    """*
    ForexService provide access to time series data
    """

    @staticmethod
    def GetTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.ForexService/GetTimeSeries',
            finazon__grpc__python_dot_forex__pb2.GetForexTimeSeriesRequest.SerializeToString,
            finazon__grpc__python_dot_forex__pb2.GetForexTimeSeriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
