# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/publishers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$finazon_grpc_python/publishers.proto\x12\x07\x66inazon\"+\n\rPublisherItem\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x14GetPublishersRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"?\n\x15GetPublishersResponse\x12&\n\x06result\x18\x01 \x03(\x0b\x32\x16.finazon.PublisherItem2d\n\x10PublisherService\x12P\n\rGetPublishers\x12\x1d.finazon.GetPublishersRequest\x1a\x1e.finazon.GetPublishersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.publishers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PUBLISHERITEM']._serialized_start=49
  _globals['_PUBLISHERITEM']._serialized_end=92
  _globals['_GETPUBLISHERSREQUEST']._serialized_start=94
  _globals['_GETPUBLISHERSREQUEST']._serialized_end=163
  _globals['_GETPUBLISHERSRESPONSE']._serialized_start=165
  _globals['_GETPUBLISHERSRESPONSE']._serialized_end=228
  _globals['_PUBLISHERSERVICE']._serialized_start=230
  _globals['_PUBLISHERSERVICE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
