# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import publishers_pb2 as finazon__grpc__python_dot_publishers__pb2


class PublisherServiceStub(object):
    """*
    PublisherService provide access to Finazon publishers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPublishers = channel.unary_unary(
                '/finazon.PublisherService/GetPublishers',
                request_serializer=finazon__grpc__python_dot_publishers__pb2.GetPublishersRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_publishers__pb2.GetPublishersResponse.FromString,
                )


class PublisherServiceServicer(object):
    """*
    PublisherService provide access to Finazon publishers
    """

    def GetPublishers(self, request, context):
        """Get a list of all publishers available at Finazon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublisherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPublishers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublishers,
                    request_deserializer=finazon__grpc__python_dot_publishers__pb2.GetPublishersRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_publishers__pb2.GetPublishersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.PublisherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PublisherService(object):
    """*
    PublisherService provide access to Finazon publishers
    """

    @staticmethod
    def GetPublishers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.PublisherService/GetPublishers',
            finazon__grpc__python_dot_publishers__pb2.GetPublishersRequest.SerializeToString,
            finazon__grpc__python_dot_publishers__pb2.GetPublishersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
