# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import sec_pb2 as finazon__grpc__python_dot_sec__pb2


class SecServiceStub(object):
    """*
    SecService provide access to SEC EDGAR filings API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFilings = channel.unary_unary(
                '/finazon.SecService/GetFilings',
                request_serializer=finazon__grpc__python_dot_sec__pb2.GetSecFillingsRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_sec__pb2.GetSecFillingsResponse.FromString,
                )


class SecServiceServicer(object):
    """*
    SecService provide access to SEC EDGAR filings API
    """

    def GetFilings(self, request, context):
        """Real-time and historical access to all forms, filings, and exhibits directly from the SEC's EDGAR system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFilings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilings,
                    request_deserializer=finazon__grpc__python_dot_sec__pb2.GetSecFillingsRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_sec__pb2.GetSecFillingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.SecService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecService(object):
    """*
    SecService provide access to SEC EDGAR filings API
    """

    @staticmethod
    def GetFilings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.SecService/GetFilings',
            finazon__grpc__python_dot_sec__pb2.GetSecFillingsRequest.SerializeToString,
            finazon__grpc__python_dot_sec__pb2.GetSecFillingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
