"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetSecFillingsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CIK_FIELD_NUMBER: builtins.int
    TICKER_FIELD_NUMBER: builtins.int
    FORM_TYPE_FIELD_NUMBER: builtins.int
    FILLED_FROM_TS_FIELD_NUMBER: builtins.int
    FILLED_TO_TS_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    CQS_FIELD_NUMBER: builtins.int
    CUSIP_FIELD_NUMBER: builtins.int
    ISIN_FIELD_NUMBER: builtins.int
    COMPOSITE_FIGI_FIELD_NUMBER: builtins.int
    SHARE_FIGI_FIELD_NUMBER: builtins.int
    LEI_FIELD_NUMBER: builtins.int
    cik: builtins.int
    ticker: builtins.str
    filled_from_ts: builtins.int
    filled_to_ts: builtins.int
    page: builtins.int
    page_size: builtins.int
    cqs: builtins.str
    cusip: builtins.str
    isin: builtins.str
    composite_figi: builtins.str
    share_figi: builtins.str
    lei: builtins.str
    @property
    def form_type(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        cik: builtins.int = ...,
        ticker: builtins.str = ...,
        form_type: collections.abc.Iterable[builtins.str] | None = ...,
        filled_from_ts: builtins.int = ...,
        filled_to_ts: builtins.int = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        cqs: builtins.str = ...,
        cusip: builtins.str = ...,
        isin: builtins.str = ...,
        composite_figi: builtins.str = ...,
        share_figi: builtins.str = ...,
        lei: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cik", b"cik", "composite_figi", b"composite_figi", "cqs", b"cqs", "cusip", b"cusip", "filled_from_ts", b"filled_from_ts", "filled_to_ts", b"filled_to_ts", "form_type", b"form_type", "isin", b"isin", "lei", b"lei", "page", b"page", "page_size", b"page_size", "share_figi", b"share_figi", "ticker", b"ticker"]) -> None: ...

global___GetSecFillingsRequest = GetSecFillingsRequest

@typing.final
class GetSecFillingsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SecFillingsItem]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___SecFillingsItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___GetSecFillingsResponse = GetSecFillingsResponse

@typing.final
class SecFillingsItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    CIK_FIELD_NUMBER: builtins.int
    FORM_TYPE_FIELD_NUMBER: builtins.int
    FILED_AT_FIELD_NUMBER: builtins.int
    FILING_URL_FIELD_NUMBER: builtins.int
    FILES_FIELD_NUMBER: builtins.int
    cik: builtins.int
    form_type: builtins.str
    filed_at: builtins.int
    filing_url: builtins.str
    @property
    def ticker(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SecFilingFile]: ...
    def __init__(
        self,
        *,
        ticker: collections.abc.Iterable[builtins.str] | None = ...,
        cik: builtins.int = ...,
        form_type: builtins.str = ...,
        filed_at: builtins.int = ...,
        filing_url: builtins.str = ...,
        files: collections.abc.Iterable[global___SecFilingFile] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cik", b"cik", "filed_at", b"filed_at", "files", b"files", "filing_url", b"filing_url", "form_type", b"form_type", "ticker", b"ticker"]) -> None: ...

global___SecFillingsItem = SecFillingsItem

@typing.final
class SecFilingFile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    name: builtins.str
    size: builtins.int
    type: builtins.str
    url: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        size: builtins.int = ...,
        type: builtins.str = ...,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "size", b"size", "type", b"type", "url", b"url"]) -> None: ...

global___SecFilingFile = SecFilingFile
