# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/sec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66inazon_grpc_python/sec.proto\x12\x07\x66inazon\"\xf9\x01\n\x15GetSecFillingsRequest\x12\x0b\n\x03\x63ik\x18\x01 \x01(\x03\x12\x0e\n\x06ticker\x18\x03 \x01(\t\x12\x11\n\tform_type\x18\x04 \x03(\t\x12\x16\n\x0e\x66illed_from_ts\x18\x05 \x01(\x03\x12\x14\n\x0c\x66illed_to_ts\x18\x06 \x01(\x03\x12\x0c\n\x04page\x18\x07 \x01(\x05\x12\x11\n\tpage_size\x18\x08 \x01(\x05\x12\x0b\n\x03\x63qs\x18\t \x01(\t\x12\r\n\x05\x63usip\x18\n \x01(\t\x12\x0c\n\x04isin\x18\x0b \x01(\t\x12\x16\n\x0e\x63omposite_figi\x18\x0c \x01(\t\x12\x12\n\nshare_figi\x18\r \x01(\t\x12\x0b\n\x03lei\x18\x0e \x01(\t\"B\n\x16GetSecFillingsResponse\x12(\n\x06result\x18\x01 \x03(\x0b\x32\x18.finazon.SecFillingsItem\"\x8e\x01\n\x0fSecFillingsItem\x12\x0e\n\x06ticker\x18\x01 \x03(\t\x12\x0b\n\x03\x63ik\x18\x02 \x01(\x03\x12\x11\n\tform_type\x18\x03 \x01(\t\x12\x10\n\x08\x66iled_at\x18\x04 \x01(\x03\x12\x12\n\nfiling_url\x18\x05 \x01(\t\x12%\n\x05\x66iles\x18\x06 \x03(\x0b\x32\x16.finazon.SecFilingFile\"F\n\rSecFilingFile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t2]\n\nSecService\x12O\n\nGetFilings\x12\x1e.finazon.GetSecFillingsRequest\x1a\x1f.finazon.GetSecFillingsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.sec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETSECFILLINGSREQUEST']._serialized_start=43
  _globals['_GETSECFILLINGSREQUEST']._serialized_end=292
  _globals['_GETSECFILLINGSRESPONSE']._serialized_start=294
  _globals['_GETSECFILLINGSRESPONSE']._serialized_end=360
  _globals['_SECFILLINGSITEM']._serialized_start=363
  _globals['_SECFILLINGSITEM']._serialized_end=505
  _globals['_SECFILINGFILE']._serialized_start=507
  _globals['_SECFILINGFILE']._serialized_end=577
  _globals['_SECSERVICE']._serialized_start=579
  _globals['_SECSERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
