# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/sip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66inazon_grpc_python/sip.proto\x12\x07\x66inazon\"\x84\x01\n\rSipTradesItem\x12\x12\n\ntrade_date\x18\x01 \x01(\x03\x12\x15\n\rmarket_center\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x03\x12\x18\n\x10sales_conditions\x18\x06 \x01(\t\"\xa3\x02\n\x13GetSipTradesRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x0b\n\x03mic\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0e\n\x06market\x18\x04 \x01(\t\x12\x10\n\x08start_at\x18\x05 \x01(\x03\x12\x0e\n\x06\x65nd_at\x18\x06 \x01(\x03\x12\x0c\n\x04tape\x18\x07 \x01(\t\x12\x0c\n\x04page\x18\x08 \x01(\x05\x12\x11\n\tpage_size\x18\t \x01(\x05\x12\r\n\x05order\x18\n \x01(\t\x12\x0b\n\x03\x63qs\x18\x0b \x01(\t\x12\x0b\n\x03\x63ik\x18\x0c \x01(\t\x12\r\n\x05\x63usip\x18\r \x01(\t\x12\x0c\n\x04isin\x18\x0e \x01(\t\x12\x16\n\x0e\x63omposite_figi\x18\x0f \x01(\t\x12\x12\n\nshare_figi\x18\x10 \x01(\t\x12\x0b\n\x03lei\x18\x11 \x01(\t\">\n\x14GetSipTradesResponse\x12&\n\x06result\x18\x01 \x03(\x0b\x32\x16.finazon.SipTradesItem\"\x1b\n\x19GetSipMarketCenterRequest\"1\n\x13SipMarketCenterItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"J\n\x1aGetSipMarketCenterResponse\x12,\n\x06result\x18\x01 \x03(\x0b\x32\x1c.finazon.SipMarketCenterItem2\xb6\x01\n\nSipService\x12J\n\tGetTrades\x12\x1c.finazon.GetSipTradesRequest\x1a\x1d.finazon.GetSipTradesResponse\"\x00\x12\\\n\x0fGetMarketCenter\x12\".finazon.GetSipMarketCenterRequest\x1a#.finazon.GetSipMarketCenterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.sip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SIPTRADESITEM']._serialized_start=43
  _globals['_SIPTRADESITEM']._serialized_end=175
  _globals['_GETSIPTRADESREQUEST']._serialized_start=178
  _globals['_GETSIPTRADESREQUEST']._serialized_end=469
  _globals['_GETSIPTRADESRESPONSE']._serialized_start=471
  _globals['_GETSIPTRADESRESPONSE']._serialized_end=533
  _globals['_GETSIPMARKETCENTERREQUEST']._serialized_start=535
  _globals['_GETSIPMARKETCENTERREQUEST']._serialized_end=562
  _globals['_SIPMARKETCENTERITEM']._serialized_start=564
  _globals['_SIPMARKETCENTERITEM']._serialized_end=613
  _globals['_GETSIPMARKETCENTERRESPONSE']._serialized_start=615
  _globals['_GETSIPMARKETCENTERRESPONSE']._serialized_end=689
  _globals['_SIPSERVICE']._serialized_start=692
  _globals['_SIPSERVICE']._serialized_end=874
# @@protoc_insertion_point(module_scope)
