"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TickerStocksInfo(google.protobuf.message.Message):
    """Stocks"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    COUNTRY_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    PUBLISHER_FIELD_NUMBER: builtins.int
    PUBLISHER_NAME_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    country: builtins.str
    currency: builtins.str
    publisher: builtins.str
    """string mic = 4;"""
    publisher_name: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        country: builtins.str = ...,
        currency: builtins.str = ...,
        publisher: builtins.str = ...,
        publisher_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["country", b"country", "currency", b"currency", "publisher", b"publisher", "publisher_name", b"publisher_name", "ticker", b"ticker"]) -> None: ...

global___TickerStocksInfo = TickerStocksInfo

@typing.final
class FindTickersStocksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    PUBLISHER_FIELD_NUMBER: builtins.int
    COUNTRY_FIELD_NUMBER: builtins.int
    MIC_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    CQS_FIELD_NUMBER: builtins.int
    CIK_FIELD_NUMBER: builtins.int
    CUSIP_FIELD_NUMBER: builtins.int
    ISIN_FIELD_NUMBER: builtins.int
    COMPOSITE_FIGI_FIELD_NUMBER: builtins.int
    SHARE_FIGI_FIELD_NUMBER: builtins.int
    LEI_FIELD_NUMBER: builtins.int
    DATASET_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    publisher: builtins.str
    country: builtins.str
    mic: builtins.str
    page: builtins.int
    page_size: builtins.int
    cqs: builtins.str
    cik: builtins.str
    cusip: builtins.str
    isin: builtins.str
    composite_figi: builtins.str
    share_figi: builtins.str
    lei: builtins.str
    dataset: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        publisher: builtins.str = ...,
        country: builtins.str = ...,
        mic: builtins.str = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        cqs: builtins.str = ...,
        cik: builtins.str = ...,
        cusip: builtins.str = ...,
        isin: builtins.str = ...,
        composite_figi: builtins.str = ...,
        share_figi: builtins.str = ...,
        lei: builtins.str = ...,
        dataset: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cik", b"cik", "composite_figi", b"composite_figi", "country", b"country", "cqs", b"cqs", "cusip", b"cusip", "dataset", b"dataset", "isin", b"isin", "lei", b"lei", "mic", b"mic", "page", b"page", "page_size", b"page_size", "publisher", b"publisher", "share_figi", b"share_figi", "ticker", b"ticker"]) -> None: ...

global___FindTickersStocksRequest = FindTickersStocksRequest

@typing.final
class FindTickersStocksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TickerStocksInfo]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___TickerStocksInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___FindTickersStocksResponse = FindTickersStocksResponse

@typing.final
class TickerCryptoInfo(google.protobuf.message.Message):
    """Crypto"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    PUBLISHER_FIELD_NUMBER: builtins.int
    PUBLISHER_NAME_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    publisher: builtins.str
    publisher_name: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        publisher: builtins.str = ...,
        publisher_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["publisher", b"publisher", "publisher_name", b"publisher_name", "ticker", b"ticker"]) -> None: ...

global___TickerCryptoInfo = TickerCryptoInfo

@typing.final
class FindTickersCryptoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    PUBLISHER_FIELD_NUMBER: builtins.int
    MARKET_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    publisher: builtins.str
    market: builtins.str
    page: builtins.int
    page_size: builtins.int
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        publisher: builtins.str = ...,
        market: builtins.str = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["market", b"market", "page", b"page", "page_size", b"page_size", "publisher", b"publisher", "ticker", b"ticker"]) -> None: ...

global___FindTickersCryptoRequest = FindTickersCryptoRequest

@typing.final
class FindTickersCryptoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TickerCryptoInfo]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___TickerCryptoInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___FindTickersCryptoResponse = FindTickersCryptoResponse

@typing.final
class TickerForexInfo(google.protobuf.message.Message):
    """Forex"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ticker", b"ticker"]) -> None: ...

global___TickerForexInfo = TickerForexInfo

@typing.final
class FindTickersForexRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    page: builtins.int
    page_size: builtins.int
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page", b"page", "page_size", b"page_size", "ticker", b"ticker"]) -> None: ...

global___FindTickersForexRequest = FindTickersForexRequest

@typing.final
class FindTickersForexResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TickerForexInfo]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___TickerForexInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___FindTickersForexResponse = FindTickersForexResponse

@typing.final
class TickerUSInfo(google.protobuf.message.Message):
    """US tickers"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    CURRENCY_FIELD_NUMBER: builtins.int
    SECURITY_FIELD_NUMBER: builtins.int
    MIC_FIELD_NUMBER: builtins.int
    ASSET_TYPE_FIELD_NUMBER: builtins.int
    CIK_FIELD_NUMBER: builtins.int
    COMPOSITE_FIGI_FIELD_NUMBER: builtins.int
    SHARE_FIGI_FIELD_NUMBER: builtins.int
    LEI_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    currency: builtins.str
    security: builtins.str
    mic: builtins.str
    asset_type: builtins.str
    cik: builtins.str
    composite_figi: builtins.str
    share_figi: builtins.str
    lei: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        currency: builtins.str = ...,
        security: builtins.str = ...,
        mic: builtins.str = ...,
        asset_type: builtins.str = ...,
        cik: builtins.str = ...,
        composite_figi: builtins.str = ...,
        share_figi: builtins.str = ...,
        lei: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["asset_type", b"asset_type", "cik", b"cik", "composite_figi", b"composite_figi", "currency", b"currency", "lei", b"lei", "mic", b"mic", "security", b"security", "share_figi", b"share_figi", "ticker", b"ticker"]) -> None: ...

global___TickerUSInfo = TickerUSInfo

@typing.final
class FindTickersUSRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKER_FIELD_NUMBER: builtins.int
    MIC_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    CQS_FIELD_NUMBER: builtins.int
    CIK_FIELD_NUMBER: builtins.int
    CUSIP_FIELD_NUMBER: builtins.int
    ISIN_FIELD_NUMBER: builtins.int
    COMPOSITE_FIGI_FIELD_NUMBER: builtins.int
    SHARE_FIGI_FIELD_NUMBER: builtins.int
    LEI_FIELD_NUMBER: builtins.int
    ticker: builtins.str
    mic: builtins.str
    page: builtins.int
    page_size: builtins.int
    cqs: builtins.str
    cik: builtins.str
    cusip: builtins.str
    isin: builtins.str
    composite_figi: builtins.str
    share_figi: builtins.str
    lei: builtins.str
    def __init__(
        self,
        *,
        ticker: builtins.str = ...,
        mic: builtins.str = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        cqs: builtins.str = ...,
        cik: builtins.str = ...,
        cusip: builtins.str = ...,
        isin: builtins.str = ...,
        composite_figi: builtins.str = ...,
        share_figi: builtins.str = ...,
        lei: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cik", b"cik", "composite_figi", b"composite_figi", "cqs", b"cqs", "cusip", b"cusip", "isin", b"isin", "lei", b"lei", "mic", b"mic", "page", b"page", "page_size", b"page_size", "share_figi", b"share_figi", "ticker", b"ticker"]) -> None: ...

global___FindTickersUSRequest = FindTickersUSRequest

@typing.final
class FindTickersUSResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TickerUSInfo]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___TickerUSInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___FindTickersUSResponse = FindTickersUSResponse
