# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from finazon_grpc_python import trade_pb2 as finazon__grpc__python_dot_trade__pb2


class TradeServiceStub(object):
    """*
    TradeService provide access to Finazon trades
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrades = channel.unary_unary(
                '/finazon.TradeService/GetTrades',
                request_serializer=finazon__grpc__python_dot_trade__pb2.GetTradesRequest.SerializeToString,
                response_deserializer=finazon__grpc__python_dot_trade__pb2.GetTradesResponse.FromString,
                )


class TradeServiceServicer(object):
    """*
    TradeService provide access to Finazon trades
    """

    def GetTrades(self, request, context):
        """Returns general information on executed trades
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrades,
                    request_deserializer=finazon__grpc__python_dot_trade__pb2.GetTradesRequest.FromString,
                    response_serializer=finazon__grpc__python_dot_trade__pb2.GetTradesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finazon.TradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TradeService(object):
    """*
    TradeService provide access to Finazon trades
    """

    @staticmethod
    def GetTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finazon.TradeService/GetTrades',
            finazon__grpc__python_dot_trade__pb2.GetTradesRequest.SerializeToString,
            finazon__grpc__python_dot_trade__pb2.GetTradesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
