"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TradesItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADE_DATE_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    trade_date: builtins.int
    price: builtins.float
    quantity: builtins.int
    def __init__(
        self,
        *,
        trade_date: builtins.int = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["price", b"price", "quantity", b"quantity", "trade_date", b"trade_date"]) -> None: ...

global___TradesItem = TradesItem

@typing_extensions.final
class GetTradesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLISHER_FIELD_NUMBER: builtins.int
    TICKER_FIELD_NUMBER: builtins.int
    MIC_FIELD_NUMBER: builtins.int
    COUNTRY_FIELD_NUMBER: builtins.int
    MARKET_FIELD_NUMBER: builtins.int
    START_AT_FIELD_NUMBER: builtins.int
    END_AT_FIELD_NUMBER: builtins.int
    TAPE_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    CQS_FIELD_NUMBER: builtins.int
    CIK_FIELD_NUMBER: builtins.int
    CUSIP_FIELD_NUMBER: builtins.int
    ISIN_FIELD_NUMBER: builtins.int
    COMPOSITE_FIGI_FIELD_NUMBER: builtins.int
    SHARE_FIGI_FIELD_NUMBER: builtins.int
    LEI_FIELD_NUMBER: builtins.int
    publisher: builtins.str
    ticker: builtins.str
    mic: builtins.str
    country: builtins.str
    market: builtins.str
    start_at: builtins.int
    end_at: builtins.int
    tape: builtins.str
    page: builtins.int
    page_size: builtins.int
    order: builtins.str
    cqs: builtins.str
    cik: builtins.str
    cusip: builtins.str
    isin: builtins.str
    composite_figi: builtins.str
    share_figi: builtins.str
    lei: builtins.str
    def __init__(
        self,
        *,
        publisher: builtins.str = ...,
        ticker: builtins.str = ...,
        mic: builtins.str = ...,
        country: builtins.str = ...,
        market: builtins.str = ...,
        start_at: builtins.int = ...,
        end_at: builtins.int = ...,
        tape: builtins.str = ...,
        page: builtins.int = ...,
        page_size: builtins.int = ...,
        order: builtins.str = ...,
        cqs: builtins.str = ...,
        cik: builtins.str = ...,
        cusip: builtins.str = ...,
        isin: builtins.str = ...,
        composite_figi: builtins.str = ...,
        share_figi: builtins.str = ...,
        lei: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cik", b"cik", "composite_figi", b"composite_figi", "country", b"country", "cqs", b"cqs", "cusip", b"cusip", "end_at", b"end_at", "isin", b"isin", "lei", b"lei", "market", b"market", "mic", b"mic", "order", b"order", "page", b"page", "page_size", b"page_size", "publisher", b"publisher", "share_figi", b"share_figi", "start_at", b"start_at", "tape", b"tape", "ticker", b"ticker"]) -> None: ...

global___GetTradesRequest = GetTradesRequest

@typing_extensions.final
class GetTradesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    @property
    def result(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TradesItem]: ...
    def __init__(
        self,
        *,
        result: collections.abc.Iterable[global___TradesItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result", b"result"]) -> None: ...

global___GetTradesResponse = GetTradesResponse
